apiVersion: v1
kind: Service
metadata:
  name: trino-service
spec:
  selector:
    app: trino
  type: ClusterIP
  ports:
  - name: trino-service
    # port = porta do service
    port: 8080
    # targetport = porta do container
    targetPort: 8080
    protocol: TCP